<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        html, body {
            height: 100%;
        }
        body {
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            background: #f1f1f1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <!-- 12. Welcome message -->
    <h1>🔐🏴‍☠️ Very Secured Page</h1>
    <h2>Welcome, <?= $user['username'] ?>!</h2>

    <p>Lorem ipsum dolorem sit amet!</p>
    <!-- 14. Admin-only link (if isAdmin() returns true) -->
    <?php if (isAdmin()) : ?>
        <!-- 15. User clicks /admin-only -->
        <a href="/admin-only">Admin Only Page</a>
    <?php endif; ?>
    
    <!-- 13. Logout link -->
    <!-- 17. User clicks /logout -->
    <a href="/logout">Logout</a>

    
</body>
</html>