<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link rel="stylesheet" href="../styles.css">
    <style>
        body {
            font-family: sans-serif;
            padding: 1rem;
            background-color: #f9f9f9;
        }

        form {
            background-color: #fff;
            max-width: 400px;
            margin: 0 auto;
            padding: 1rem;
            border-radius: 8px;
            border: 1px solid #ccc;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);

            .input-group {
                display: flex;
                flex-direction: column;
                gap: 0.5rem;
                margin-bottom: 1rem;
            }

            footer {
                display: flex;
                justify-content: space-between;
            }
        }
    </style>
</head>

<body>
    <form action="calculate.php" method="post">
        <header>
            <h1>Calculator</h1>
        </header>

        <div class="input-group">
            <?php foreach ($numbers as $number): ?>
                <input type="number" name="numbers[]" value="<?= $number ?>">
            <?php endforeach; ?>
        </div>

        <footer>
            <button type="button">Add number</button>

            <select name="operation" required>
                <option value="add" <?= markSelected('add') ?>>Add</option>
                <option value="subtract" <?= markSelected('subtract') ?>>Subtract</option>
                <option value="multiply" <?= markSelected('multiply') ?>>Multiply</option>
                <option value="divide" <?= markSelected('divide') ?>>Divide</option>
                <option value="power" <?= markSelected('power') ?>>Power</option>
            </select>

            <button>Calculate</button>
        </footer>
        <h2><?= $result ?></h2>
    </form>


    <script>
        const inputContainer = document.querySelector('.input-group');

        document.querySelector('button[type="button"]').addEventListener('click', () => {
            const newInput = document.createElement('input');
            newInput.type = 'number';
            newInput.name = 'numbers[]';
            inputContainer.appendChild(newInput);
        });
    </script>
</body>

</html>