<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forms</title>
    <link rel="stylesheet" href="../styles.css">
</head>

<body>
    <h1>What's your name?</h1>

    <!-- <form method="post" action="/greet.php"> -->
    <form method="get" action="/greet.php">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>
        <button type="submit">Submit</button>
    </form>

    <ul>
        <?php foreach ($defaultNames as $name) : ?>
            <li>
                <a href="/greet.php?name=<?= $name ?>">
                    <?= $name ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</body>

</html>