<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        html, body {
            height: 100%;
        }
        body {
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            background: #f1f1f1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <!-- 19. protected.view.phtml — Secured Page UI -->
    <!-- 20. Displays a message and a logout link -->
    <h1>🔐🏴‍☠️ Very Secured Page</h1>
    <p>Lorem ipsum dolorem sit amet!</p>
    <!-- 22. logout.php — Session Destroyer -->
    <a href="logout.php">Logout</a>
    
    <!-- 21. Only shown if user is authenticated -->
</body>
</html>